package com.notash.cryptobacktester.ai

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private val aiPanel = Color(0xFF0B1020)
private val aiCyan = Color(0xFF22D3EE)
private val aiText = Color(0xFFF5F7FF)
private val aiMuted = Color(0xFF8490A7)

@Composable
fun AiStrategyBuilderPage(
    fa: Boolean,
    onGenerate: (String) -> Unit,
    onUseForBacktest: () -> Unit,
    onSave: () -> Unit
) {
    var prompt by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<StrategyPackage?>(null) }
    LazyColumn(Modifier.fillMaxSize().padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
        item { Text(if (fa) "ساخت استراتژی با هوش مصنوعی" else "AI STRATEGY BUILDER", color = aiCyan, fontSize = 24.sp) }
        item { Text(if (fa) "استراتژی را با زبان طبیعی توضیح بده؛ قبل از بک‌تست باید اعتبارسنجی شود." else "Describe the strategy in natural language; it must be validated before backtesting.", color = aiMuted, fontSize = 10.sp) }
        item { OutlinedTextField(prompt, { prompt = it }, Modifier.fillMaxWidth().height(170.dp), label = { Text(if (fa) "استراتژی مورد نظر شما" else "Describe your strategy") }) }
        item { Button(onClick = { onGenerate(prompt) }, enabled = prompt.isNotBlank(), modifier = Modifier.fillMaxWidth()) { Text(if (fa) "تبدیل به استراتژی قابل بک‌تست" else "GENERATE TESTABLE STRATEGY") } }
        generated?.let { s ->
            item { Card(colors = CardDefaults.cardColors(containerColor = aiPanel)) { Column(Modifier.padding(14.dp)) { Text(s.name, color = aiText, fontSize = 18.sp); Text(s.description, color = aiMuted, fontSize = 11.sp); Text(if (fa) "ورود: ${s.entryRules.joinToString(" | ")}" else "Entry: ${s.entryRules.joinToString(" | ")}", color = aiText, fontSize = 10.sp); Text(if (fa) "خروج: ${s.exitRules.joinToString(" | ")}" else "Exit: ${s.exitRules.joinToString(" | ")}", color = aiText, fontSize = 10.sp); Text("SL ${s.stopLoss} • TP ${s.takeProfit} • Risk ${s.riskPercent}% • ${s.leverage}x", color = aiCyan, fontSize = 10.sp) } } }
            item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(6.dp)) { Button(onClick = onUseForBacktest, modifier = Modifier.weight(1f)) { Text(if (fa) "بک‌تست" else "BACKTEST") }; OutlinedButton(onClick = onSave, modifier = Modifier.weight(1f)) { Text(if (fa) "ذخیره نسخه" else "SAVE VERSION") } } }
        }
    }
}
