package com.notash.cryptobacktester.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.notash.cryptobacktester.core.Candle
import com.notash.cryptobacktester.core.Side
import com.notash.cryptobacktester.core.TradeResult
import com.notash.cryptobacktester.data.CoinExRepository
import com.notash.cryptobacktester.intelligence.PumpDumpDetector
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.math.abs

private val Z0=Color(0xFF050912);private val Z1=Color(0xFF0B1422);private val Z2=Color(0xFF111D2D);private val ZT=Color(0xFFF5F7FB);private val ZM=Color(0xFF7F8DA3);private val ZV=Color(0xFF8A45FF);private val ZC=Color(0xFF26D9FF);private val ZG=Color(0xFF21D79B);private val ZR=Color(0xFFFF536F);private val ZY=Color(0xFFFFC857)
private data class ZQuote(val s:String,val p:Double,val c:Double,val v:Double)

@Composable
fun AlvexPremiumReplacement(themeMode:AppThemeMode,onTheme:(AppThemeMode)->Unit){
    var page by rememberSaveable{mutableStateOf(0)};var pair by rememberSaveable{mutableStateOf("BTCUSDT")};var tf by rememberSaveable{mutableStateOf("15min")};var fa by rememberSaveable{mutableStateOf(true)};var settings by rememberSaveable{mutableStateOf(false)};var quotes by remember{mutableStateOf<List<ZQuote>>(emptyList())}
    val repo=remember{CoinExRepository()};val vm=remember{BacktestViewModel()};val state by vm.state.collectAsState();val scope=rememberCoroutineScope()
    fun refresh(){scope.launch{quotes=withContext(Dispatchers.IO){listOf("BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT","PEPEUSDT").mapNotNull{s->runCatching{repo.loadLatestTicker(s)}.getOrNull()?.let{ZQuote(s,it.last,it.changeRate*100,it.volume)}}}}}
    LaunchedEffect(Unit){refresh()}
    MaterialTheme(colorScheme=darkColorScheme(primary=ZV,secondary=ZC,background=Z0,surface=Z1,onBackground=ZT,onSurface=ZT)){
        if(settings){ZSettings(fa,themeMode,onTheme,{fa=!fa}){settings=false};return@MaterialTheme}
        Scaffold(containerColor=Z0,topBar={ZHeader(page,fa,{page=3},{settings=true},{fa=!fa})},bottomBar={ZNav(page,fa){page=it}}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(page){0->ZHome(fa,quotes,{pair=it;page=2});1->ZMarkets(fa,quotes,{pair=it;page=2;vm.setMarket(it)},refresh);2->ZTerminal(fa,pair,{pair=it;vm.setMarket(it)},tf,{tf=it},vm,state);else->ZIntel(fa,pair,repo)}}}}
    }
}

@Composable private fun ZHeader(page:Int,fa:Boolean,ai:()->Unit,settings:()->Unit,lang:()->Unit){Row(Modifier.fillMaxWidth().height(64.dp).background(Z0),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=ai){Icon(Icons.Outlined.Star,null,tint=ZC)};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Text("ALVEX",color=ZT,fontSize=19.sp,fontWeight=FontWeight.Black,letterSpacing=2.sp);Text(if(fa)listOf("خانه","بازار","معاملات و بک‌تست","هوش بازار")[page]else listOf("Home","Markets","Trading Terminal","Intelligence")[page],color=ZM,fontSize=8.sp)};TextButton(onClick=lang){Text(if(fa)"EN"else"FA",color=ZC,fontSize=9.sp)};IconButton(onClick=settings){Icon(Icons.Outlined.Settings,null,tint=ZT)}}}
@Composable private fun ZNav(page:Int,fa:Boolean,go:(Int)->Unit){NavigationBar(containerColor=Z1,tonalElevation=0.dp){listOf(Triple(0,Icons.Outlined.Home,if(fa)"خانه"else"Home"),Triple(1,Icons.Outlined.List,if(fa)"بازار"else"Markets"),Triple(2,Icons.Outlined.Build,if(fa)"بک‌تست"else"Terminal"),Triple(3,Icons.Outlined.Info,if(fa)"هوش"else"Intel")).forEach{(i,ic,t)->NavigationBarItem(page==i,{go(i)},icon={Icon(ic,t)},label={Text(t,fontSize=8.sp)})}}}
@Composable private fun ZHome(fa:Boolean,qs:List<ZQuote>,open:(String)->Unit){val btc=qs.firstOrNull{it.s=="BTCUSDT"};val movers=qs.sortedByDescending{it.c}.take(4);LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(26.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Box(Modifier.fillMaxWidth().height(170.dp).background(Brush.linearGradient(listOf(Color(0xFF21104F),Z1,Color(0xFF061B27))),RoundedCornerShape(26.dp))){Column(Modifier.padding(18.dp)){Text("MARKET OVERVIEW",color=ZM,fontSize=8.sp,letterSpacing=1.sp);Spacer(Modifier.height(5.dp));Text("BTC / USDT",color=ZT,fontSize=12.sp);Text(btc?.let{money(it.p)}?:"—",color=ZT,fontSize=30.sp,fontWeight=FontWeight.Black);Text(btc?.let{pct(it.c)}?:"Waiting for market data",color=if((btc?.c?:0.0)>=0)ZG else ZR,fontSize=10.sp);Spacer(Modifier.height(9.dp));Spark(movers.map{it.c})}}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Stat("BTC",btc?.let{money(it.p)}?:"—",btc?.let{pct(it.c)}?:"—",if((btc?.c?:0.0)>=0)ZG else ZR,Modifier.weight(1f));Stat("24H VOL",qs.firstOrNull()?.let{compact(it.v)}?:"—","CoinEx",ZC,Modifier.weight(1f));Stat("RADAR",if(qs.isEmpty())"WAIT"else"READY","AI",ZV,Modifier.weight(1f))}};item{Text("TOP MOVERS",color=ZT,fontSize=15.sp,fontWeight=FontWeight.Black)};items(movers){q->Market(q){open(q.s)}};item{Text("AI MARKET RADAR",color=ZT,fontSize=15.sp,fontWeight=FontWeight.Black)};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Radar("PUMP / DUMP",ZV,Modifier.weight(1f));Radar("WHALE",ZC,Modifier.weight(1f));Radar("MEME",ZY,Modifier.weight(1f))}}}}
@Composable private fun ZMarkets(fa:Boolean,qs:List<ZQuote>,open:(String)->Unit,refresh:()->Unit){var q by rememberSaveable{mutableStateOf("")};val list=qs.filter{q.isBlank()||it.s.contains(q.uppercase())};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text(if(fa)"بازار"else"MARKETS",color=ZT,fontSize=20.sp,fontWeight=FontWeight.Black)};item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text(if(fa)"جستجوی ارز"else"Search asset")},leadingIcon={Icon(Icons.Outlined.Search,null)},shape=RoundedCornerShape(16.dp))};items(list){x->Market(x){open(x.s)}};item{OutlinedButton(onClick=refresh,Modifier.fillMaxWidth()){Text("Refresh")}}}}
@Composable private fun ZTerminal(fa:Boolean,pair:String,onPair:(String)->Unit,tf:String,onTf:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){val repo=remember{CoinExRepository()};val scope=rememberCoroutineScope();var cs by remember{mutableStateOf<List<Candle>>(emptyList())};var selected by remember{mutableStateOf<Int?>(null)};fun load(){scope.launch{cs=runCatching{repo.loadKlines(pair,tf,220)}.getOrDefault(emptyList())}};LaunchedEffect(pair,tf){load()};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(pair.replace("USDT"," / USDT"),color=ZT,fontSize=20.sp,fontWeight=FontWeight.Black);Text("CoinEx • OHLC",color=ZM,fontSize=8.sp)};Text(if(state.isRunning)"RUNNING"else"READY",color=if(state.isRunning)ZY else ZG,fontWeight=FontWeight.Bold)}};item{Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("1min","5min","15min","1h","4h","1D").forEach{v->FilterChip(tf==v,{onTf(v)},label={Text(v,fontSize=7.sp)})}}};item{Chart(cs,state.report?.trades?:emptyList(),selected,{selected=it},Modifier.fillMaxWidth().height(330.dp))};item{selected?.let{i->cs.getOrNull(i)?.let{Ohlc(it)}}};item{Controls(fa,pair,onPair,vm,state)};item{Report(state.report)};item{state.report?.let{Trades(it.trades)}}}}
@Composable private fun Controls(fa:Boolean,pair:String,onPair:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){var amount by rememberSaveable{mutableStateOf("1000")};var lev by rememberSaveable{mutableStateOf("3")};var risk by rememberSaveable{mutableStateOf(state.riskPercent.toString())};Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Column(Modifier.padding(13.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(if(fa)"تنظیمات بک‌تست"else"BACKTEST CONFIG",color=ZT,fontWeight=FontWeight.Black);OutlinedTextField(pair,{onPair(it.uppercase())},Modifier.fillMaxWidth(),singleLine=true,label={Text("Pair")});Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(amount,{amount=it},Modifier.weight(1f),singleLine=true,label={Text("Amount")});OutlinedTextField(lev,{lev=it},Modifier.weight(1f),singleLine=true,label={Text("Leverage")})};OutlinedTextField(risk,{risk=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Risk %")});Button(onClick={vm.setRiskPercent(risk.toDoubleOrNull()?:1.0);vm.setLeverage(lev.toDoubleOrNull()?:3.0);vm.runBacktest()},Modifier.fillMaxWidth(),enabled=!state.isRunning){Text(if(fa)"اجرای بک‌تست واقعی"else"Run real backtest")};Text(state.error?:state.status,color=if(state.error!=null)ZR else ZM,fontSize=8.sp)}}}
@Composable private fun Chart(cs:List<Candle>,ts:List<TradeResult>,selected:Int?,pick:(Int)->Unit,m:Modifier){if(cs.isEmpty()){Box(m.clip(RoundedCornerShape(20.dp)).background(Z2),contentAlignment=Alignment.Center){Text("Loading real CoinEx candles…",color=ZM)};return};Canvas(m.clip(RoundedCornerShape(20.dp)).background(Z2).pointerInput(cs){detectTapGestures{p->pick(((p.x/size.width)*cs.size).toInt().coerceIn(0,cs.lastIndex))}}){val lo=cs.minOf{it.low};val hi=cs.maxOf{it.high};val range=(hi-lo).takeIf{it>0}?:1.0;val step=size.width/cs.size;val body=(step*.6f).coerceAtLeast(2f);fun y(v:Double)=size.height-((v-lo)/range*size.height).toFloat();cs.forEachIndexed{i,c->val x=i*step+step/2;val col=if(c.close>=c.open)ZG else ZR;drawLine(col,Offset(x,y(c.high)),Offset(x,y(c.low)),1.2f);drawRect(col,Offset(x-body/2,y(maxOf(c.open,c.close))),androidx.compose.ui.geometry.Size(body,maxOf(2f,abs(y(c.open)-y(c.close)))))};ts.forEach{t->val ei=cs.indices.minByOrNull{abs(cs[it].timestamp-t.entryTime)}?:return@forEach;val x=ei*step+step/2;val col=if(t.side==Side.LONG)ZG else ZR;drawCircle(col,5f,Offset(x,y(t.entryPrice)));val ex=cs.indices.minByOrNull{abs(cs[it].timestamp-t.exitTime)};if(ex!=null){val xx=ex*step+step/2;drawCircle(ZY,4f,Offset(xx,y(t.exitPrice)));drawLine(col,Offset(x,y(t.entryPrice)),Offset(xx,y(t.exitPrice)),1f)}};selected?.let{i->drawLine(ZT,Offset(i*step+step/2,0f),Offset(i*step+step/2,size.height),1f)}}}
@Composable private fun Trades(ts:List<TradeResult>){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("TRADE DIAGNOSTICS",color=ZT,fontWeight=FontWeight.Black);ts.takeLast(20).asReversed().forEach{t->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Column(Modifier.padding(10.dp)){Text("${t.side.name}  ${money(t.entryPrice)} → ${money(t.exitPrice)}",color=ZT,fontSize=9.sp,fontWeight=FontWeight.Bold);Text("SL ${money(t.stopLoss)} • TP ${money(t.takeProfit)} • ${t.exitReason}",color=ZM,fontSize=8.sp);Text("PnL %+.3f • Fee %.4f • Funding %.4f".format(t.netPnl,t.fees,t.funding),color=if(t.netPnl>=0)ZG else ZR,fontSize=8.sp)}}}}}
@Composable private fun Report(r:BacktestReport?){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Column(Modifier.padding(13.dp)){Text("AI BACKTEST ANALYST",color=ZT,fontWeight=FontWeight.Black);Spacer(Modifier.height(7.dp));Text("ROI ${r?.let{"%.2f%%".format(it.roiPercent)}?:"—"}   Win ${r?.let{"%.1f%%".format(it.winRatePercent)}?:"—"}   PF ${r?.let{if(it.profitFactor.isInfinite())"∞" else "%.2f".format(it.profitFactor)}?:"—"}   DD ${r?.let{"%.2f%%".format(it.maxDrawdownPercent)}?:"—"}",color=if((r?.netPnl?:0.0)>=0)ZG else ZR,fontSize=10.sp)}}}
@Composable private fun ZIntel(fa:Boolean,pair:String,repo:CoinExRepository){var score by remember{mutableStateOf(0)};var text by remember{mutableStateOf(if(fa)"در انتظار داده واقعی..."else"Waiting for live data...")};LaunchedEffect(pair){val cs=runCatching{repo.loadKlines(pair,"15min",120)}.getOrDefault(emptyList());val s=PumpDumpDetector().analyze(cs);if(s!=null){score=s.score.toInt();text="${s.direction} • ${"%.2f".format(s.priceChangePercent)}% • volume x${"%.1f".format(s.volumeRatio)}"}};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text(if(fa)"هوش بازار"else"INTELLIGENCE HUB",color=ZT,fontSize=20.sp,fontWeight=FontWeight.Black)};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(24.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Gauge(score);Text(pair,color=ZT,fontSize=21.sp,fontWeight=FontWeight.Black);Text(text,color=ZM,fontSize=9.sp)}}};item{Intel("PUMP / DUMP RADAR","Price acceleration • volume anomaly • score",ZV)};item{Intel("WHALE INTELLIGENCE","Provider-neutral smart-money layer",ZC)};item{Intel("MEME / SHITCOIN SCANNER","Liquidity • volatility • concentration • risk",ZY)};item{Intel("COIN INTELLIGENCE","Tokenomics • project • team • roadmap • on-chain",ZG)};item{Intel("AI TRADE ANALYST","Backtest diagnostics",ZV)}}}
@Composable private fun XSettingsDummy(){ }
@Composable private fun ZSettings(fa:Boolean,mode:AppThemeMode,onMode:(AppThemeMode)->Unit,language:()->Unit,back:()->Unit){Column(Modifier.fillMaxSize().background(Z0)){Row(Modifier.padding(8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Outlined.ArrowBack,null,tint=ZT)};Text("ALVEX • Settings",color=ZT,fontWeight=FontWeight.Black)};Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Setting("Account & Security","Session • API-key policy",Icons.Outlined.Person);Setting("Notifications","Pump/Dump • Whale • AI",Icons.Outlined.Notifications);Setting("Language",if(fa)"فارسی / English"else"English / فارسی",Icons.Outlined.Language,language);Row(verticalAlignment=Alignment.CenterVertically){Text("Theme",color=ZT,modifier=Modifier.weight(1f));Switch(checked=mode==AppThemeMode.LIGHT,onCheckedChange={onMode(if(it)AppThemeMode.LIGHT else AppThemeMode.DARK)})};Setting("Share & Reports","CSV • JSON • AI report",Icons.Outlined.Share)}}}
@Composable private fun Setting(t:String,s:String,ic:androidx.compose.ui.graphics.vector.ImageVector,on:(()->Unit)?=null){Card(onClick=on?:{},Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(ic,null,tint=ZC);Spacer(Modifier.width(9.dp));Column{Text(t,color=ZT,fontWeight=FontWeight.Bold);Text(s,color=ZM,fontSize=8.sp)}}}}
@Composable private fun Radar(t:String,c:Color,m:Modifier){Card(m,shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=Z2)){Column(Modifier.padding(9.dp)){Pill(t,c)}}}
@Composable private fun Pill(t:String,c:Color){Text(t,color=c,fontSize=7.sp,fontWeight=FontWeight.Black,modifier=Modifier.background(c.copy(.12f),RoundedCornerShape(20.dp)).padding(horizontal=7.dp,vertical=4.dp))}
@Composable private fun Stat(t:String,v:String,s:String,c:Color,m:Modifier){Card(m,shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Column(Modifier.padding(9.dp)){Text(t,color=ZM,fontSize=7.sp);Text(v,color=ZT,fontSize=10.sp,fontWeight=FontWeight.Black);Text(s,color=c,fontSize=7.sp)}}}
@Composable private fun Market(q:XQuote,on:()->Unit){Card(onClick=on,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Row(Modifier.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(38.dp).clip(RoundedCornerShape(12.dp)).background(Brush.linearGradient(listOf(ZV.copy(.2f),ZC.copy(.1f)))),contentAlignment=Alignment.Center){Text(q.s.take(1),color=ZT,fontWeight=FontWeight.Black)};Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(q.s.removeSuffix("USDT"),color=ZT,fontWeight=FontWeight.Bold);Text("/ USDT",color=ZM,fontSize=7.sp)};Column(horizontalAlignment=Alignment.End){Text(money(q.p),color=ZT,fontSize=9.sp);Text(pct(q.c),color=if(q.c>=0)ZG else ZR,fontSize=9.sp)}}}}
@Composable private fun Ohlc(c:Candle){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=Z1)){Row(Modifier.fillMaxWidth().padding(9.dp),horizontalArrangement=Arrangement.SpaceEvenly){Text("O ${money(c.open)}",color=ZT,fontSize=8.sp);Text("H ${money(c.high)}",color=ZG,fontSize=8.sp);Text("L ${money(c.low)}",color=ZR,fontSize=8.sp);Text("C ${money(c.close)}",color=ZT,fontSize=8.sp);Text("V ${compact(c.volume)}",color=ZM,fontSize=8.sp)}}}
@Composable private fun Gauge(score:Int){Canvas(Modifier.size(125.dp)){drawCircle(Color(0xFF1B2B3D),size.minDimension*.34f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(2f));drawCircle(if(score>=70)ZR else ZV,size.minDimension*.18f,center)}}
@Composable private fun Spark(v:List<Double>){Canvas(Modifier.fillMaxWidth().height(30.dp)){if(v.size<2)return@Canvas;val lo=v.minOrNull()?:0.0;val hi=v.maxOrNull()?:1.0;val r=(hi-lo).takeIf{it>0}?:1.0;var last=Offset(0f,size.height);v.forEachIndexed{i,x->val p=Offset(size.width*i/v.lastIndex.toFloat(),size.height-((x-lo)/r*size.height).toFloat());if(i>0)drawLine(ZC,last,p,2f);last=p}}}
private fun money(v:Double)=if(v>=1000)"%,.2f".format(v)else if(v>=1)"%.4f".format(v)else"%.8f".format(v)
private fun pct(v:Double)="%+.2f%%".format(v)
private fun compact(v:Double)=when{v>=1e9->"%.1fB".format(v/1e9);v>=1e6->"%.1fM".format(v/1e6);v>=1e3->"%.1fK".format(v/1e3);else->"%.0f".format(v)}
