package com.notash.cryptobacktester.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.notash.cryptobacktester.core.BacktestReport
import com.notash.cryptobacktester.core.Candle
import com.notash.cryptobacktester.core.Side
import com.notash.cryptobacktester.core.TradeResult
import com.notash.cryptobacktester.data.CoinExRepository
import com.notash.cryptobacktester.intelligence.PumpDumpDetector
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.math.abs

private val C0=Color(0xFF050912); private val C1=Color(0xFF0B1422); private val C2=Color(0xFF111D2D); private val CT=Color(0xFFF5F7FB); private val CM=Color(0xFF7F8DA3); private val CP=Color(0xFF8A45FF); private val CC=Color(0xFF26D9FF); private val CG=Color(0xFF21D79B); private val CR=Color(0xFFFF536F); private val CY=Color(0xFFFFC857)
private data class Quote(val symbol:String,val price:Double,val change:Double,val volume:Double)

@Composable fun AlvexPremiumWorkspaceClean(themeMode:AppThemeMode,onThemeMode:(AppThemeMode)->Unit){
    var tab by rememberSaveable{mutableStateOf(0)}; var market by rememberSaveable{mutableStateOf("BTCUSDT")}; var tf by rememberSaveable{mutableStateOf("15min")}; var fa by rememberSaveable{mutableStateOf(true)}; var settings by rememberSaveable{mutableStateOf(false)}
    val vm=remember{BacktestViewModel()}; val state by vm.state.collectAsState(); val repo=remember{CoinExRepository()}; val scope=rememberCoroutineScope(); var quotes by remember{mutableStateOf<List<Quote>>(emptyList())}
    fun refresh(){scope.launch{quotes=withContext(Dispatchers.IO){listOf("BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT","PEPEUSDT").mapNotNull{s->runCatching{repo.loadLatestTicker(s)}.getOrNull()?.let{Quote(s,it.last,it.changeRate*100,it.volume)}}}}}
    LaunchedEffect(Unit){refresh()}
    MaterialTheme(colorScheme=darkColorScheme(primary=CP,secondary=CC,background=C0,surface=C1,onBackground=CT,onSurface=CT)){
        if(settings){CleanSettings(fa,themeMode,onThemeMode,{fa=!fa}){settings=false};return@MaterialTheme}
        Scaffold(containerColor=C0,topBar={CleanHeader(tab,fa,{tab=3},{settings=true},{fa=!fa})},bottomBar={CleanNav(tab,fa){tab=it}}){pad->Box(Modifier.fillMaxSize().padding(pad).background(C0)){when(tab){0->CleanHome(fa,quotes,state.report,{market=it;tab=2},::refresh);1->CleanMarkets(fa,quotes,{market=it;vm.setMarket(it);tab=2},::refresh);2->CleanTerminal(fa,market,{market=it;vm.setMarket(it)},tf,{tf=it},vm,state);else->CleanIntel(fa,market,repo)}}}}
    }
}

@Composable private fun CleanHeader(tab:Int,fa:Boolean,onAi:()->Unit,onSettings:()->Unit,onLang:()->Unit){Row(Modifier.fillMaxWidth().height(64.dp).background(C0).padding(horizontal=9.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onAi){Icon(Icons.Outlined.Star,null,tint=CC)};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(23.dp).clip(RoundedCornerShape(6.dp)).background(Brush.linearGradient(listOf(CP,CC))),contentAlignment=Alignment.Center){Text("A",color=Color.White,fontWeight=FontWeight.Black)};Spacer(Modifier.width(6.dp));Text("ALVEX",color=CT,fontWeight=FontWeight.Black,letterSpacing=2.sp)};Text(if(fa)listOf("خانه","بازار","معاملات و بک‌تست","هوش بازار")[tab]else listOf("Home","Markets","Trading Terminal","Intelligence")[tab],color=CM,fontSize=8.sp)};TextButton(onClick=onLang){Text(if(fa)"EN"else"FA",color=CC,fontSize=9.sp)};IconButton(onClick=onSettings){Icon(Icons.Outlined.Settings,null,tint=CT)}}}
@Composable private fun CleanNav(tab:Int,fa:Boolean,onSelect:(Int)->Unit){NavigationBar(containerColor=C1,tonalElevation=0.dp){listOf(Triple(0,Icons.Outlined.Home,if(fa)"خانه"else"Home"),Triple(1,Icons.Outlined.List,if(fa)"بازار"else"Markets"),Triple(2,Icons.Outlined.Build,if(fa)"بک‌تست"else"Terminal"),Triple(3,Icons.Outlined.Info,if(fa)"هوش"else"Intel")).forEach{(i,ic,l)->NavigationBarItem(tab==i,{onSelect(i)},icon={Icon(ic,l)},label={Text(l,fontSize=8.sp)})}}}

@Composable private fun CleanHome(fa:Boolean,quotes:List<Quote>,report:BacktestReport?,openMarket:(String)->Unit,refresh:()->Unit){val btc=quotes.firstOrNull{it.symbol=="BTCUSDT"};val movers=quotes.sortedByDescending{it.change}.take(4);LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=20.dp)){item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(26.dp),colors=CardDefaults.cardColors(containerColor=C1)){Box(Modifier.fillMaxWidth().height(150.dp).background(Brush.linearGradient(listOf(Color(0xFF1C1045),C1,Color(0xFF071925))),RoundedCornerShape(26.dp))){Column(Modifier.padding(17.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("MARKET OVERVIEW",color=CM,fontSize=8.sp,letterSpacing=1.sp);Spacer(Modifier.weight(1f));Pill("LIVE",CG)};Spacer(Modifier.height(8.dp));Text("BTC / USDT",color=CT,fontSize=12.sp);Text(btc?.let{money(it.price)}?:"—",color=CT,fontSize=29.sp,fontWeight=FontWeight.Black);Text(btc?.let{pct(it.change)}?:"Waiting for market data",color=if((btc?.change?:0.0)>=0)CG else CR,fontSize=10.sp);Spacer(Modifier.height(8.dp));Spark(movers.map{it.change},Modifier.fillMaxWidth().height(32.dp))}}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Stat("BTC",btc?.let{money(it.price)}?:"—",btc?.let{pct(it.change)}?:"—",if((btc?.change?:0)>=0)CG else CR,Modifier.weight(1f));Stat("24H VOL",quotes.firstOrNull()?.let{compact(it.volume)}?:"—","CoinEx",CC,Modifier.weight(1f));Stat("RADAR",if(quotes.isEmpty())"WAIT"else"READY","AI",CP,Modifier.weight(1f))}};item{Section("TOP MOVERS",if(fa)"حرکت‌های مهم بازار"else"Live market movers")};items(movers){q->MarketRow(q){openMarket(q.symbol)}};item{Section("AI MARKET RADAR","Pump/Dump • Whale • Meme • Coin Intelligence")};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(13.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Radar("PUMP / DUMP","Signal engine",CP,Modifier.weight(1f));Radar("WHALE","Provider layer",CC,Modifier.weight(1f));Radar("MEME","Risk scanner",CY,Modifier.weight(1f))}}}};item{Section(if(fa)"آخرین بک‌تست"else"LATEST BACKTEST","Real metrics")};item{Report(report)}}}

@Composable private fun CleanMarkets(fa:Boolean,quotes:List<Quote>,open:(String)->Unit,refresh:()->Unit){var q by rememberSaveable{mutableStateOf("")};val list=quotes.filter{q.isBlank()||it.symbol.contains(q.uppercase())};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Section(if(fa)"بازار"else"MARKETS","Crypto • Futures • Favorites")};item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text(if(fa)"جستجوی ارز"else"Search asset")},leadingIcon={Icon(Icons.Outlined.Search,null)},shape=RoundedCornerShape(16.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Favorites","Crypto","Futures","Forex").forEach{FilterChip(it=="Crypto",{},label={Text(it,fontSize=8.sp)})}}};items(list){x->MarketRow(x){open(x.symbol)}};item{OutlinedButton(onClick=refresh,Modifier.fillMaxWidth()){Icon(Icons.Outlined.Refresh,null);Spacer(Modifier.width(5.dp));Text("Refresh")}}}}

@Composable private fun CleanTerminal(fa:Boolean,market:String,onMarket:(String)->Unit,tf:String,onTf:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){val repo=remember{CoinExRepository()};val scope=rememberCoroutineScope();var candles by remember{mutableStateOf<List<Candle>>(emptyList())};var selected by remember{mutableStateOf<Int?>(null)};fun load(){scope.launch{candles=runCatching{repo.loadKlines(market,tf,220)}.getOrDefault(emptyList())}};LaunchedEffect(market,tf){vm.setMarket(market);vm.setTimeframe(tf);load()};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(9.dp),contentPadding=PaddingValues(bottom=22.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(market.replace("USDT"," / USDT"),color=CT,fontSize=20.sp,fontWeight=FontWeight.Black);Text("CoinEx • real OHLC",color=CM,fontSize=8.sp)};Pill(if(state.isRunning)"RUNNING"else"READY",if(state.isRunning)CY else CG)}};item{Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("1min","5min","15min","1h","4h","1D").forEach{v->FilterChip(tf==v,{onTf(v)},label={Text(v,fontSize=7.sp)})}}};item{Candles(candles,state.report?.trades?:emptyList(),selected,{selected=it},Modifier.fillMaxWidth().height(320.dp))};item{selected?.let{i->candles.getOrNull(i)?.let{Ohlc(it)}}};item{Controls(fa,market,onMarket,vm,state)};item{Report(state.report)};item{state.report?.let{Trades(it.trades,fa)}}}}

@Composable private fun Controls(fa:Boolean,market:String,onMarket:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){var amount by rememberSaveable{mutableStateOf("1000")};var risk by rememberSaveable{mutableStateOf(state.riskPercent.toString())};var lev by rememberSaveable{mutableStateOf(state.leverage.toString())};Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(13.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(if(fa)"تنظیمات بک‌تست"else"BACKTEST CONFIG",color=CT,fontWeight=FontWeight.Black);OutlinedTextField(market,{onMarket(it.uppercase())},Modifier.fillMaxWidth(),singleLine=true,label={Text("Pair")});Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(amount,{amount=it},Modifier.weight(1f),singleLine=true,label={Text("Amount")});OutlinedTextField(lev,{lev=it},Modifier.weight(1f),singleLine=true,label={Text("Leverage")})};OutlinedTextField(risk,{risk=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Risk %")});Button(onClick={vm.setRiskPercent(risk.toDoubleOrNull()?:1.0);vm.setLeverage(lev.toDoubleOrNull()?:3.0);vm.runBacktest()},Modifier.fillMaxWidth(),enabled=!state.isRunning,shape=RoundedCornerShape(14.dp)){Icon(Icons.Outlined.PlayArrow,null);Spacer(Modifier.width(5.dp));Text(if(fa)"اجرای بک‌تست واقعی"else"Run real backtest")};Text(state.error?:state.status,color=if(state.error!=null)CR else CM,fontSize=8.sp)}}}

@Composable private fun CleanIntel(fa:Boolean,market:String,repo:CoinExRepository){var candles by remember{mutableStateOf<List<Candle>>(emptyList())};var text by remember{mutableStateOf(if(fa)"در انتظار داده واقعی..."else"Waiting for live data...")};var score by remember{mutableStateOf(0)};LaunchedEffect(market){candles=runCatching{repo.loadKlines(market,"15min",120)}.getOrDefault(emptyList());val s=PumpDumpDetector().analyze(candles);if(s!=null){score=s.score.toInt();text="${s.direction} • ${"%.2f".format(s.priceChangePercent)}% • volume x${"%.1f".format(s.volumeRatio)}"}};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Section(if(fa)"هوش بازار"else"INTELLIGENCE HUB","AI Radar • Whale • Pump/Dump • Meme • Coin Intelligence")};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Gauge(score);Text(market,color=CT,fontSize=22.sp,fontWeight=FontWeight.Black);Text(text,color=CM,fontSize=9.sp);Text(if(fa)"فقط داده قابل‌اندازه‌گیری؛ پیش‌بینی قطعی نیست."else"Measurable data only; no guaranteed prediction.",color=CM,fontSize=8.sp)}}};item{Intel("PUMP / DUMP RADAR","Price acceleration • volume anomaly • score",CP)};item{Intel("WHALE INTELLIGENCE","Provider-neutral smart-money layer",CC)};item{Intel("MEME / SHITCOIN SCANNER","Liquidity • volatility • concentration • risk",CY)};item{Intel("COIN INTELLIGENCE","Tokenomics • project • team • roadmap • on-chain",CG)};item{Intel("AI TRADE ANALYST","Backtest diagnostics and optimization context",CP)}}}

@Composable private fun Candles(cs:List<Candle>,ts:List<TradeResult>,selected:Int?,onSelect:(Int)->Unit,m:Modifier){if(cs.isEmpty()){Box(m.clip(RoundedCornerShape(20.dp)).background(C2),contentAlignment=Alignment.Center){Text("Loading real CoinEx candles…",color=CM)};return};Canvas(m.clip(RoundedCornerShape(20.dp)).background(C2).pointerInput(cs){detectTapGestures{p->onSelect(((p.x/size.width)*cs.size).toInt().coerceIn(0,cs.lastIndex))}}){val min=cs.minOf{it.low};val max=cs.maxOf{it.high};val r=(max-min).takeIf{it>0}?:1.0;val step=size.width/cs.size;val body=(step*.6f).coerceAtLeast(2f);fun y(v:Double)=size.height-((v-min)/r*size.height).toFloat();for(i in 0..3){val gy=size.height*i/3f;drawLine(VBorder(),Offset(0f,gy),Offset(size.width,gy),1f)};cs.forEachIndexed{i,c->val x=i*step+step/2;val col=if(c.close>=c.open)CG else CR;drawLine(col,Offset(x,y(c.high)),Offset(x,y(c.low)),1.2f);drawRect(col,Offset(x-body/2,y(maxOf(c.open,c.close))),androidx.compose.ui.geometry.Size(body,maxOf(2f,abs(y(c.open)-y(c.close)))))};ts.forEach{t->val ei=cs.indices.minByOrNull{abs(cs[it].timestamp-t.entryTime)}?:return@forEach;val x=ei*step+step/2;val col=if(t.side==Side.LONG)CG else CR;drawCircle(col,5f,Offset(x,y(t.entryPrice)));val ex=cs.indices.minByOrNull{abs(cs[it].timestamp-t.exitTime)};if(ex!=null){val xx=ex*step+step/2;drawCircle(CY,4f,Offset(xx,y(t.exitPrice)));drawLine(col,Offset(x,y(t.entryPrice)),Offset(xx,y(t.exitPrice)),1f)}};selected?.let{i->val x=i*step+step/2;drawLine(CT,Offset(x,0f),Offset(x,size.height),1f)}}}

@Composable private fun Trades(ts:List<TradeResult>,fa:Boolean){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text(if(fa)"معاملات و خطایابی ربات"else"TRADE DIAGNOSTICS",color=CT,fontWeight=FontWeight.Black);ts.takeLast(25).asReversed().forEach{t->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){Pill(t.side.name,if(t.side==Side.LONG)CG else CR);Spacer(Modifier.width(8.dp));Text("${money(t.entryPrice)} → ${money(t.exitPrice)}",color=CT,fontSize=9.sp);Spacer(Modifier.weight(1f));Text("%+.3f".format(t.netPnl),color=if(t.netPnl>=0)CG else CR,fontWeight=FontWeight.Black,fontSize=9.sp)};Text("SL ${money(t.stopLoss)} • TP ${money(t.takeProfit)} • ${t.exitReason}",color=CM,fontSize=8.sp);Text("Qty ${"%.5f".format(t.quantity)} • Fee ${"%.4f".format(t.fees)} • Funding ${"%.4f".format(t.funding)}",color=CM,fontSize=7.sp)}}}}}

@Composable private fun Report(r:BacktestReport?){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(13.dp)){Text("AI BACKTEST ANALYST",color=CT,fontWeight=FontWeight.Black);Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){Metric("ROI",r?.let{"%.2f%%".format(it.roiPercent)}?:"—");Metric("WIN",r?.let{"%.1f%%".format(it.winRatePercent)}?:"—");Metric("PF",r?.let{if(it.profitFactor.isInfinite())"∞" else "%.2f".format(it.profitFactor)}?:"—");Metric("DD",r?.let{"%.2f%%".format(it.maxDrawdownPercent)}?:"—")};Spacer(Modifier.height(7.dp));Equity(r?.equityCurve?:emptyList(),Modifier.fillMaxWidth().height(60.dp))}}}
@Composable private fun CleanSettings(fa:Boolean,mode:AppThemeMode,onMode:(AppThemeMode)->Unit,toggle:()->Unit,back:()->Unit){Column(Modifier.fillMaxSize().background(C0)){Row(Modifier.fillMaxWidth().padding(8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Outlined.ArrowBack,null,tint=CT)};Column{Text("ALVEX",color=CT,fontWeight=FontWeight.Black);Text(if(fa)"تنظیمات"else"Settings",color=CM,fontSize=8.sp)}};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Setting("Account & Security","Session • password • secure API-key policy",Icons.Outlined.Person)};item{Setting("Notifications","Pump/Dump • Whale • AI alerts",Icons.Outlined.Notifications)};item{Setting("Language",if(fa)"فارسی / English"else"English / فارسی",Icons.Outlined.Language,toggle)};item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Theme",color=CT,fontWeight=FontWeight.Bold);Text(if(mode==AppThemeMode.DARK)"Dark"else"Light",color=CM,fontSize=8.sp)};Switch(checked=mode==AppThemeMode.LIGHT,onCheckedChange={onMode(if(it)AppThemeMode.LIGHT else AppThemeMode.DARK)})}};item{Setting("Share & Reports","CSV • JSON • AI report • Android share",Icons.Outlined.Share)};item{Setting("About ALVEX","Professional crypto intelligence workspace",Icons.Outlined.Info)}}}}
@Composable private fun Setting(title:String,sub:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:(()->Unit)?=null){Card(onClick=onClick?:{},Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=C1)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=CC);Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(title,color=CT,fontWeight=FontWeight.Bold);Text(sub,color=CM,fontSize=8.sp)};Icon(Icons.Outlined.Info,null,tint=CM,modifier=Modifier.size(15.dp))}}}
@Composable private fun Section(title:String,sub:String=""){Column{Text(title,color=CT,fontSize=15.sp,fontWeight=FontWeight.Black);if(sub.isNotBlank())Text(sub,color=CM,fontSize=8.sp)}}
@Composable private fun Pill(t:String,c:Color){Box(Modifier.clip(RoundedCornerShape(30.dp)).background(c.copy(.12f)).padding(horizontal=8.dp,vertical=4.dp)){Text(t,color=c,fontSize=7.sp,fontWeight=FontWeight.Black)}}
@Composable private fun Stat(t:String,v:String,s:String,c:Color,m:Modifier){Card(m,shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=C1)){Column(Modifier.padding(9.dp)){Text(t,color=CM,fontSize=7.sp);Text(v,color=CT,fontSize=10.sp,fontWeight=FontWeight.Black);Text(s,color=c,fontSize=7.sp)}}}
@Composable private fun MarketRow(q:Quote,onClick:()->Unit){Card(onClick=onClick,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=C1)){Row(Modifier.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(12.dp)).background(Brush.linearGradient(listOf(CP.copy(.22f),CC.copy(.12f)))),contentAlignment=Alignment.Center){Text(q.symbol.take(1),color=CT,fontWeight=FontWeight.Black)};Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(q.symbol.removeSuffix("USDT"),color=CT,fontWeight=FontWeight.Bold);Text("/ USDT • ${compact(q.volume)} vol",color=CM,fontSize=7.sp)};Column(horizontalAlignment=Alignment.End){Text(money(q.price),color=CT,fontSize=9.sp,fontWeight=FontWeight.Bold);Text(pct(q.change),color=if(q.change>=0)CG else CR,fontSize=9.sp)}}}}
@Composable private fun Radar(t:String,s:String,c:Color,m:Modifier){Card(m,shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=C2)){Column(Modifier.padding(9.dp)){Pill("•",c);Spacer(Modifier.height(4.dp));Text(t,color=CT,fontSize=8.sp,fontWeight=FontWeight.Bold);Text(s,color=CM,fontSize=6.sp)}}}
@Composable private fun Intel(t:String,s:String,c:Color){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=C1)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(11.dp)).background(c.copy(.12f)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Info,null,tint=c)};Spacer(Modifier.width(9.dp));Column{Text(t,color=CT,fontSize=10.sp,fontWeight=FontWeight.Black);Text(s,color=CM,fontSize=7.sp)}}}}
@Composable private fun Metric(t:String,v:String){Column(Modifier.weight(1f)){Text(t,color=CM,fontSize=7.sp);Text(v,color=CT,fontSize=9.sp,fontWeight=FontWeight.Black)}}
@Composable private fun Ohlc(c:Candle){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=C1)){Row(Modifier.fillMaxWidth().padding(9.dp),horizontalArrangement=Arrangement.SpaceEvenly){Text("O ${money(c.open)}",color=CT,fontSize=8.sp);Text("H ${money(c.high)}",color=CG,fontSize=8.sp);Text("L ${money(c.low)}",color=CR,fontSize=8.sp);Text("C ${money(c.close)}",color=CT,fontSize=8.sp);Text("V ${compact(c.volume)}",color=CM,fontSize=8.sp)}}}
@Composable private fun Gauge(score:Int){Canvas(Modifier.size(125.dp)){for(i in 1..3)drawCircle(VBorder(),size.minDimension*.34f*i/3f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(1f));drawCircle(if(score>=70)CR else CP,size.minDimension*.18f,center);drawCircle(CC,size.minDimension*.34f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(2f))}}
@Composable private fun Equity(v:List<Double>,m:Modifier){Canvas(m){if(v.size<2)return@Canvas;val min=v.minOrNull()?:0.0;val max=v.maxOrNull()?:1.0;val r=(max-min).takeIf{it>0}?:1.0;for(i in 1 until v.size){val x1=size.width*(i-1)/v.lastIndex;val x2=size.width*i/v.lastIndex;val y1=size.height-((v[i-1]-min)/r*size.height).toFloat();val y2=size.height-((v[i]-min)/r*size.height).toFloat();drawLine(CP,Offset(x1,y1),Offset(x2,y2),2f)}}}
@Composable private fun Spark(v:List<Double>,m:Modifier){Canvas(m){if(v.size<2)return@Canvas;val min=v.minOrNull()?:0.0;val max=v.maxOrNull()?:1.0;val r=(max-min).takeIf{it>0}?:1.0;var last=Offset(0f,size.height);v.forEachIndexed{i,x->val p=Offset(size.width*i/(v.lastIndex.toFloat()),size.height-((x-min)/r*size.height).toFloat());if(i>0)drawLine(CC,last,p,2f);last=p}}}
private fun VBorder()=Color(0xFF1B2B3D)
private fun money(v:Double)=if(v>=1000)"%,.2f".format(v)else if(v>=1)"%.4f".format(v)else"%.8f".format(v)
private fun pct(v:Double)="%+.2f%%".format(v)
private fun compact(v:Double)=when{v>=1e9->"%.1fB".format(v/1e9);v>=1e6->"%.1fM".format(v/1e6);v>=1e3->"%.1fK".format(v/1e3);else->"%.0f".format(v)}
