package com.notash.cryptobacktester.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.notash.cryptobacktester.core.BacktestReport
import com.notash.cryptobacktester.core.Candle
import com.notash.cryptobacktester.core.Side
import com.notash.cryptobacktester.core.TradeResult
import com.notash.cryptobacktester.data.CoinExRepository
import com.notash.cryptobacktester.intelligence.PumpDumpDetector
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.math.abs

private val AF_BG=Color(0xFF050912)
private val AF_PANEL=Color(0xFF0B1422)
private val AF_PANEL2=Color(0xFF111D2D)
private val AF_TEXT=Color(0xFFF5F7FB)
private val AF_MUTED=Color(0xFF7F8DA3)
private val AF_PURPLE=Color(0xFF8A45FF)
private val AF_CYAN=Color(0xFF26D9FF)
private val AF_GREEN=Color(0xFF21D79B)
private val AF_RED=Color(0xFFFF536F)
private val AF_GOLD=Color(0xFFFFC857)
private data class AFQuote(val symbol:String,val price:Double,val change:Double,val volume:Double)

@Composable
fun AlvexPremiumFinal(themeMode:AppThemeMode,onTheme:(AppThemeMode)->Unit){
    var page by rememberSaveable{mutableStateOf(0)}
    var pair by rememberSaveable{mutableStateOf("BTCUSDT")}
    var timeframe by rememberSaveable{mutableStateOf("15min")}
    var fa by rememberSaveable{mutableStateOf(true)}
    var settings by rememberSaveable{mutableStateOf(false)}
    var quotes by remember{mutableStateOf<List<AFQuote>>(emptyList())}
    val vm=remember{BacktestViewModel()};val state by vm.state.collectAsState();val repo=remember{CoinExRepository()};val scope=rememberCoroutineScope()
    fun refresh(){scope.launch{quotes=withContext(Dispatchers.IO){listOf("BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT","PEPEUSDT").mapNotNull{s->runCatching{repo.loadLatestTicker(s)}.getOrNull()?.let{AFQuote(s,it.last,it.changeRate*100.0,it.volume)}}}}}
    LaunchedEffect(Unit){refresh()}
    MaterialTheme(colorScheme=darkColorScheme(primary=AF_PURPLE,secondary=AF_CYAN,background=AF_BG,surface=AF_PANEL,onBackground=AF_TEXT,onSurface=AF_TEXT)){
        if(settings){AFSettings(fa,themeMode,onTheme,{fa=!fa}){settings=false};return@MaterialTheme}
        Scaffold(containerColor=AF_BG,topBar={AFHeader(page,fa,{page=3},{settings=true},{fa=!fa})},bottomBar={AFBottom(page,fa){page=it}}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(page){0->AFHome(fa,quotes,state.report,{pair=it;page=2},::refresh,{page=3});1->AFMarkets(fa,quotes,{pair=it;page=2;vm.setMarket(it)},::refresh);2->AFTerminal(fa,pair,{pair=it;vm.setMarket(it)},timeframe,{timeframe=it},vm,state);else->AFIntel(fa,pair,repo)}}}
    }
}

@Composable private fun AFHeader(page:Int,fa:Boolean,ai:()->Unit,set:()->Unit,lang:()->Unit){Row(Modifier.fillMaxWidth().height(64.dp).background(AF_BG).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=ai){Icon(Icons.Outlined.Star,null,tint=AF_CYAN)};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(23.dp).clip(RoundedCornerShape(6.dp)).background(Brush.linearGradient(listOf(AF_PURPLE,AF_CYAN))),contentAlignment=Alignment.Center){Text("A",color=Color.White,fontWeight=FontWeight.Black)};Spacer(Modifier.width(6.dp));Text("ALVEX",color=AF_TEXT,fontWeight=FontWeight.Black,letterSpacing=2.sp)};Text(if(fa)listOf("خانه","بازار","معاملات و بک‌تست","هوش بازار")[page]else listOf("Home","Markets","Trading Terminal","Intelligence")[page],color=AF_MUTED,fontSize=8.sp)};TextButton(onClick=lang){Text(if(fa)"EN"else"FA",color=AF_CYAN,fontSize=9.sp)};IconButton(onClick=set){Icon(Icons.Outlined.Settings,null,tint=AF_TEXT)}}}
@Composable private fun AFBottom(page:Int,fa:Boolean,go:(Int)->Unit){NavigationBar(containerColor=AF_PANEL,tonalElevation=0.dp){listOf(Triple(0,Icons.Outlined.Home,if(fa)"خانه"else"Home"),Triple(1,Icons.Outlined.List,if(fa)"بازار"else"Markets"),Triple(2,Icons.Outlined.Build,if(fa)"بک‌تست"else"Terminal"),Triple(3,Icons.Outlined.Info,if(fa)"هوش"else"Intel")).forEach{(i,ic,l)->NavigationBarItem(page==i,{go(i)},icon={Icon(ic,l)},label={Text(l,fontSize=8.sp)})}}}

@Composable private fun AFHome(fa:Boolean,qs:List<AFQuote>,r:BacktestReport?,open:(String)->Unit,refresh:()->Unit,intel:()->Unit){val btc=qs.firstOrNull{it.symbol=="BTCUSDT"};val movers=qs.sortedByDescending{it.change}.take(4);LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=20.dp)){item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(26.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Box(Modifier.fillMaxWidth().height(155.dp).background(Brush.linearGradient(listOf(Color(0xFF1E104A),AF_PANEL,Color(0xFF071A25))),RoundedCornerShape(26.dp))){Column(Modifier.padding(17.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("MARKET OVERVIEW",color=AF_MUTED,fontSize=8.sp,letterSpacing=1.sp);Spacer(Modifier.weight(1f));AFStatus("LIVE",AF_GREEN)};Spacer(Modifier.height(7.dp));Text("BTC / USDT",color=AF_TEXT,fontSize=12.sp);Text(btc?.let{afMoney(it.price)}?:"—",color=AF_TEXT,fontSize=29.sp,fontWeight=FontWeight.Black);Text(btc?.let{afPct(it.change)}?:"Waiting for market data",color=if((btc?.change?:0.0)>=0)AF_GREEN else AF_RED,fontSize=10.sp);Spacer(Modifier.height(7.dp));AFSpark(movers.map{it.change},Modifier.fillMaxWidth().height(32.dp))}}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){AFStat("BTC",btc?.let{afMoney(it.price)}?:"—",btc?.let{afPct(it.change)}?:"—",if((btc?.change?:0.0)>=0)AF_GREEN else AF_RED,Modifier.weight(1f));AFStat("24H VOL",qs.firstOrNull()?.let{afCompact(it.volume)}?:"—","CoinEx",AF_CYAN,Modifier.weight(1f));AFStat("RADAR",if(qs.isEmpty())"WAIT"else"READY","AI",AF_PURPLE,Modifier.weight(1f))}};item{AFSection("TOP MOVERS",if(fa)"حرکت‌های مهم بازار"else"Live market movers")};items(movers){q->AFMarketRow(q){open(q.symbol)}};item{AFSection("AI MARKET RADAR","Pump/Dump • Whale • Meme • Coin Intelligence")};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){AFRadar("PUMP / DUMP",AF_PURPLE,Modifier.weight(1f),intel);AFRadar("WHALE",AF_CYAN,Modifier.weight(1f),intel);AFRadar("MEME",AF_GOLD,Modifier.weight(1f),intel)}};item{AFSection(if(fa)"آخرین بک‌تست"else"LATEST BACKTEST","Real report metrics")};item{AFReport(r)};item{OutlinedButton(onClick=refresh,Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp)){Icon(Icons.Outlined.Refresh,null);Spacer(Modifier.width(5.dp));Text(if(fa)"به‌روزرسانی داده بازار"else"Refresh market data")}}}}

@Composable private fun AFMarkets(fa:Boolean,qs:List<AFQuote>,open:(String)->Unit,refresh:()->Unit){var search by rememberSaveable{mutableStateOf("")};val list=qs.filter{search.isBlank()||it.symbol.contains(search.uppercase())};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{AFSection(if(fa)"بازار"else"MARKETS","Crypto • Futures • Favorites")};item{OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text(if(fa)"جستجوی ارز"else"Search asset")},leadingIcon={Icon(Icons.Outlined.Search,null)},shape=RoundedCornerShape(16.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Favorites","Crypto","Futures","Forex").forEach{FilterChip(it=="Crypto",{},label={Text(it,fontSize=8.sp)})}}};items(list){q->AFMarketRow(q){open(q.symbol)}};item{OutlinedButton(onClick=refresh,Modifier.fillMaxWidth()){Icon(Icons.Outlined.Refresh,null);Spacer(Modifier.width(5.dp));Text("Refresh")}}}}

@Composable private fun AFTerminal(fa:Boolean,pair:String,onPair:(String)->Unit,tf:String,onTf:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){val repo=remember{CoinExRepository()};val scope=rememberCoroutineScope();var cs by remember{mutableStateOf<List<Candle>>(emptyList())};var selected by remember{mutableStateOf<Int?>(null)};fun load(){scope.launch{cs=runCatching{repo.loadKlines(pair,tf,220)}.getOrDefault(emptyList())}};LaunchedEffect(pair,tf){vm.setMarket(pair);vm.setTimeframe(tf);load()};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(9.dp),contentPadding=PaddingValues(bottom=22.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(pair.replace("USDT"," / USDT"),color=AF_TEXT,fontSize=20.sp,fontWeight=FontWeight.Black);Text("CoinEx • real OHLC",color=AF_MUTED,fontSize=8.sp)};AFStatus(if(state.isRunning)"RUNNING"else"READY",if(state.isRunning)AF_GOLD else AF_GREEN)}};item{Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("1min","5min","15min","1h","4h","1D").forEach{v->FilterChip(tf==v,{onTf(v)},label={Text(v,fontSize=7.sp)})}}};item{AFChart(cs,state.report?.trades?:emptyList(),selected,{selected=it},Modifier.fillMaxWidth().height(325.dp))};item{selected?.let{i->cs.getOrNull(i)?.let{AFOhlc(it)}}};item{AFControls(fa,pair,onPair,vm,state)};item{AFReport(state.report)};item{state.report?.let{AFTrades(it.trades,fa)}}}}

@Composable private fun AFControls(fa:Boolean,pair:String,onPair:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){var amount by rememberSaveable{mutableStateOf("1000")};var risk by rememberSaveable{mutableStateOf(state.riskPercent.toString())};var lev by rememberSaveable{mutableStateOf(state.leverage.toString())};Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Column(Modifier.padding(13.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(if(fa)"تنظیمات بک‌تست"else"BACKTEST CONFIG",color=AF_TEXT,fontWeight=FontWeight.Black);OutlinedTextField(pair,{onPair(it.uppercase())},Modifier.fillMaxWidth(),singleLine=true,label={Text("Pair")});Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(amount,{amount=it},Modifier.weight(1f),singleLine=true,label={Text("Amount")});OutlinedTextField(lev,{lev=it},Modifier.weight(1f),singleLine=true,label={Text("Leverage")})};OutlinedTextField(risk,{risk=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Risk %")});Button(onClick={vm.setRiskPercent(risk.toDoubleOrNull()?:1.0);vm.setLeverage(lev.toDoubleOrNull()?:3.0);vm.runBacktest()},Modifier.fillMaxWidth(),enabled=!state.isRunning,shape=RoundedCornerShape(14.dp)){Icon(Icons.Outlined.PlayArrow,null);Spacer(Modifier.width(5.dp));Text(if(fa)"اجرای بک‌تست واقعی"else"Run real backtest")};Text(state.error?:state.status,color=if(state.error!=null)AF_RED else AF_MUTED,fontSize=8.sp)}}}

@Composable private fun AFIntel(fa:Boolean,pair:String,repo:CoinExRepository){var score by remember{mutableStateOf(0)};var detail by remember{mutableStateOf(if(fa)"در انتظار داده واقعی..."else"Waiting for live data...")};LaunchedEffect(pair){val cs=runCatching{repo.loadKlines(pair,"15min",120)}.getOrDefault(emptyList());val s=PumpDumpDetector().analyze(cs);if(s!=null){score=s.score.toInt();detail="${s.direction} • ${"%.2f".format(s.priceChangePercent)}% • volume x${"%.1f".format(s.volumeRatio)}"}};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{AFSection(if(fa)"هوش بازار"else"INTELLIGENCE HUB","AI Radar • Whale • Pump/Dump • Meme • Coin Intelligence")};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){AFGauge(score);Text(pair,color=AF_TEXT,fontSize=22.sp,fontWeight=FontWeight.Black);Text(detail,color=AF_MUTED,fontSize=9.sp);Text(if(fa)"داده قابل‌اندازه‌گیری؛ پیش‌بینی قطعی نیست."else"Measurable data only; no guaranteed prediction.",color=AF_MUTED,fontSize=8.sp)}}};item{AFIntel("PUMP / DUMP RADAR","Price acceleration • volume anomaly • score",AF_PURPLE)};item{AFIntel("WHALE INTELLIGENCE","Provider-neutral smart-money layer",AF_CYAN)};item{AFIntel("MEME / SHITCOIN SCANNER","Liquidity • volatility • concentration • risk",AF_GOLD)};item{AFIntel("COIN INTELLIGENCE","Tokenomics • project • team • roadmap • on-chain",AF_GREEN)};item{AFIntel("AI TRADE ANALYST","Backtest diagnostics and optimization context",AF_PURPLE)}}}

@Composable private fun AFChart(cs:List<Candle>,ts:List<TradeResult>,selected:Int?,pick:(Int)->Unit,modifier:Modifier){if(cs.isEmpty()){Box(modifier.clip(RoundedCornerShape(20.dp)).background(AF_PANEL2),contentAlignment=Alignment.Center){Text("Loading real CoinEx candles…",color=AF_MUTED)};return};Canvas(modifier.clip(RoundedCornerShape(20.dp)).background(AF_PANEL2).pointerInput(cs){detectTapGestures{p->pick(((p.x/size.width)*cs.size).toInt().coerceIn(0,cs.lastIndex))}}){val lo=cs.minOf{it.low};val hi=cs.maxOf{it.high};val range=(hi-lo).takeIf{it>0}?:1.0;val step=size.width/cs.size;val body=(step*.58f).coerceAtLeast(2f);fun y(v:Double)=size.height-((v-lo)/range*size.height).toFloat();for(i in 0..3)drawLine(Color(0xFF1B2B3D),Offset(0f,size.height*i/3f),Offset(size.width,size.height*i/3f),1f);cs.forEachIndexed{i,c->val x=i*step+step/2;val col=if(c.close>=c.open)AF_GREEN else AF_RED;drawLine(col,Offset(x,y(c.high)),Offset(x,y(c.low)),1.2f);drawRect(col,Offset(x-body/2,y(maxOf(c.open,c.close))),androidx.compose.ui.geometry.Size(body,maxOf(2f,abs(y(c.open)-y(c.close)))))};ts.forEach{t->val ei=cs.indices.minByOrNull{abs(cs[it].timestamp-t.entryTime)}?:return@forEach;val x=ei*step+step/2;val col=if(t.side==Side.LONG)AF_GREEN else AF_RED;drawCircle(col,5f,Offset(x,y(t.entryPrice)));val ex=cs.indices.minByOrNull{abs(cs[it].timestamp-t.exitTime)};if(ex!=null){val xx=ex*step+step/2;drawCircle(AF_GOLD,4f,Offset(xx,y(t.exitPrice)));drawLine(col,Offset(x,y(t.entryPrice)),Offset(xx,y(t.exitPrice)),1f)}};selected?.let{i->val x=i*step+step/2;drawLine(AF_TEXT,Offset(x,0f),Offset(x,size.height),1f)}}}

@Composable private fun AFTrades(ts:List<TradeResult>,fa:Boolean){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text(if(fa)"معاملات و خطایابی ربات"else"TRADE DIAGNOSTICS",color=AF_TEXT,fontWeight=FontWeight.Black);ts.takeLast(25).asReversed().forEach{t->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Column(Modifier.padding(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){AFStatus(t.side.name,if(t.side==Side.LONG)AF_GREEN else AF_RED);Spacer(Modifier.width(7.dp));Text("${afMoney(t.entryPrice)} → ${afMoney(t.exitPrice)}",color=AF_TEXT,fontSize=9.sp);Spacer(Modifier.weight(1f));Text("%+.3f".format(t.netPnl),color=if(t.netPnl>=0)AF_GREEN else AF_RED,fontWeight=FontWeight.Black,fontSize=9.sp)};Text("SL ${afMoney(t.stopLoss)} • TP ${afMoney(t.takeProfit)} • ${t.exitReason}",color=AF_MUTED,fontSize=8.sp);Text("Qty ${"%.5f".format(t.quantity)} • Fee ${"%.4f".format(t.fees)} • Funding ${"%.4f".format(t.funding)}",color=AF_MUTED,fontSize=7.sp)}}}}}

@Composable private fun AFReport(r:BacktestReport?){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Column(Modifier.padding(13.dp)){Text("AI BACKTEST ANALYST",color=AF_TEXT,fontWeight=FontWeight.Black);Spacer(Modifier.height(7.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){AFMetric("ROI",r?.let{"%.2f%%".format(it.roiPercent)}?:"—");AFMetric("WIN",r?.let{"%.1f%%".format(it.winRatePercent)}?:"—");AFMetric("PF",r?.let{if(it.profitFactor.isInfinite())"∞" else "%.2f".format(it.profitFactor)}?:"—");AFMetric("DD",r?.let{"%.2f%%".format(it.maxDrawdownPercent)}?:"—")}}}}
@Composable private fun AFSettings(fa:Boolean,mode:AppThemeMode,onMode:(AppThemeMode)->Unit,language:()->Unit,back:()->Unit){Column(Modifier.fillMaxSize().background(AF_BG)){Row(Modifier.fillMaxWidth().padding(8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Outlined.ArrowBack,null,tint=AF_TEXT)};Column{Text("ALVEX",color=AF_TEXT,fontWeight=FontWeight.Black);Text(if(fa)"تنظیمات"else"Settings",color=AF_MUTED,fontSize=8.sp)}};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{AFSetting("Account & Security","Session • password • API-key policy",Icons.Outlined.Person)};item{AFSetting("Notifications","Pump/Dump • Whale • AI alerts",Icons.Outlined.Notifications)};item{AFSetting("Language",if(fa)"فارسی / English"else"English / فارسی",Icons.Outlined.Language,language)};item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Theme",color=AF_TEXT,fontWeight=FontWeight.Bold);Text(if(mode==AppThemeMode.DARK)"Dark"else"Light",color=AF_MUTED,fontSize=8.sp)};Switch(checked=mode==AppThemeMode.LIGHT,onCheckedChange={onMode(if(it)AppThemeMode.LIGHT else AppThemeMode.DARK)})}};item{AFSetting("Share & Reports","CSV • JSON • AI report • Android share",Icons.Outlined.Share)};item{AFSetting("About ALVEX","Professional crypto intelligence workspace",Icons.Outlined.Info)}}}}
@Composable private fun AFSetting(title:String,subtitle:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:(()->Unit)?=null){Card(onClick=onClick?:{},Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=AF_CYAN);Spacer(Modifier.width(9.dp));Column{Text(title,color=AF_TEXT,fontWeight=FontWeight.Bold);Text(subtitle,color=AF_MUTED,fontSize=8.sp)}}}}
@Composable private fun AFSection(title:String,subtitle:String=""){Column{Text(title,color=AF_TEXT,fontSize=15.sp,fontWeight=FontWeight.Black);if(subtitle.isNotBlank())Text(subtitle,color=AF_MUTED,fontSize=8.sp)}}
@Composable private fun AFStatus(text:String,color:Color){Box(Modifier.clip(RoundedCornerShape(30.dp)).background(color.copy(.12f)).padding(horizontal=8.dp,vertical=4.dp)){Text(text,color=color,fontSize=7.sp,fontWeight=FontWeight.Black)}}
@Composable private fun AFStat(title:String,value:String,sub:String,color:Color,modifier:Modifier){Card(modifier,shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Column(Modifier.padding(9.dp)){Text(title,color=AF_MUTED,fontSize=7.sp);Text(value,color=AF_TEXT,fontSize=10.sp,fontWeight=FontWeight.Black);Text(sub,color=color,fontSize=7.sp)}}}
@Composable private fun AFMarketRow(q:AFQuote,on:()->Unit){Card(onClick=on,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Row(Modifier.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(12.dp)).background(Brush.linearGradient(listOf(AF_PURPLE.copy(.2f),AF_CYAN.copy(.1f)))),contentAlignment=Alignment.Center){Text(q.symbol.take(1),color=AF_TEXT,fontWeight=FontWeight.Black)};Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(q.symbol.removeSuffix("USDT"),color=AF_TEXT,fontWeight=FontWeight.Bold);Text("/ USDT • ${afCompact(q.volume)} vol",color=AF_MUTED,fontSize=7.sp)};Column(horizontalAlignment=Alignment.End){Text(afMoney(q.price),color=AF_TEXT,fontSize=9.sp,fontWeight=FontWeight.Bold);Text(afPct(q.change),color=if(q.change>=0)AF_GREEN else AF_RED,fontSize=9.sp)}}}}
@Composable private fun APRadar(title:String,color:Color,modifier:Modifier,on:()->Unit){Card(onClick=on,modifier=modifier,shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL2)){Column(Modifier.padding(9.dp)){AFStatus("•",color);Spacer(Modifier.height(4.dp));Text(title,color=AF_TEXT,fontSize=8.sp,fontWeight=FontWeight.Bold)}}}
@Composable private fun AFIntel(title:String,subtitle:String,color:Color){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(11.dp)).background(color.copy(.12f)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Info,null,tint=color)};Spacer(Modifier.width(9.dp));Column{Text(title,color=AF_TEXT,fontSize=10.sp,fontWeight=FontWeight.Black);Text(subtitle,color=AF_MUTED,fontSize=7.sp)}}}}
@Composable private fun AFMetric(label:String,value:String){Column(Modifier.width(70.dp)){Text(label,color=AF_MUTED,fontSize=7.sp);Text(value,color=AF_TEXT,fontSize=9.sp,fontWeight=FontWeight.Black)}}
@Composable private fun AFOhlc(c:Candle){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=AF_PANEL)){Row(Modifier.fillMaxWidth().padding(9.dp),horizontalArrangement=Arrangement.SpaceEvenly){Text("O ${afMoney(c.open)}",color=AF_TEXT,fontSize=8.sp);Text("H ${afMoney(c.high)}",color=AF_GREEN,fontSize=8.sp);Text("L ${afMoney(c.low)}",color=AF_RED,fontSize=8.sp);Text("C ${afMoney(c.close)}",color=AF_TEXT,fontSize=8.sp);Text("V ${afCompact(c.volume)}",color=AF_MUTED,fontSize=8.sp)}}}
@Composable private fun AFGauge(score:Int){Canvas(Modifier.size(125.dp)){for(i in 1..3)drawCircle(Color(0xFF1B2B3D),size.minDimension*.34f*i/3f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(1f));drawCircle(if(score>=70)AF_RED else AF_PURPLE,size.minDimension*.18f,center);drawCircle(AF_CYAN,size.minDimension*.34f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(2f))}}
@Composable private fun APSpark(values:List<Double>,modifier:Modifier){Canvas(modifier){if(values.size<2)return@Canvas;val lo=values.minOrNull()?:0.0;val hi=values.maxOrNull()?:1.0;val range=(hi-lo).takeIf{it>0}?:1.0;var last=Offset(0f,size.height);values.forEachIndexed{i,v->val p=Offset(size.width*i/values.lastIndex.toFloat(),size.height-((v-lo)/range*size.height).toFloat());if(i>0)drawLine(AF_CYAN,last,p,2f);last=p}}}
private fun afMoney(v:Double)=if(v>=1000)"%,.2f".format(v)else if(v>=1)"%.4f".format(v)else"%.8f".format(v)
private fun afPct(v:Double)="%+.2f%%".format(v)
private fun afCompact(v:Double)=when{v>=1e9->"%.1fB".format(v/1e9);v>=1e6->"%.1fM".format(v/1e6);v>=1e3->"%.1fK".format(v/1e3);else->"%.0f".format(v)}
