package com.notash.cryptobacktester.ui

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.notash.cryptobacktester.core.*
import com.notash.cryptobacktester.data.CoinExRepository
import com.notash.cryptobacktester.intelligence.PumpDumpDetector
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlin.math.abs

private val B=Color(0xFF050912);private val P=Color(0xFF0B1422);private val P2=Color(0xFF111D2D);private val T=Color(0xFFF5F7FB);private val M=Color(0xFF7F8DA3);private val V=Color(0xFF8A45FF);private val C=Color(0xFF26D9FF);private val G=Color(0xFF21D79B);private val R=Color(0xFFFF536F);private val Y=Color(0xFFFFC857)
private data class Q(val s:String,val p:Double,val c:Double,val v:Double)

@Composable fun AlvexPremiumFinal(theme:AppThemeMode,onTheme:(AppThemeMode)->Unit){var tab by rememberSaveable{mutableStateOf(0)};var pair by rememberSaveable{mutableStateOf("BTCUSDT")};var tf by rememberSaveable{mutableStateOf("15min")};var fa by rememberSaveable{mutableStateOf(true)};var settings by rememberSaveable{mutableStateOf(false)};var quotes by remember{mutableStateOf<List<Q>>(emptyList())};val repo=remember{CoinExRepository()};val vm=remember{BacktestViewModel()};val state by vm.state.collectAsState();val scope=rememberCoroutineScope();fun refresh(){scope.launch{quotes=withContext(Dispatchers.IO){listOf("BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT","PEPEUSDT").mapNotNull{s->runCatching{repo.loadLatestTicker(s)}.getOrNull()?.let{Q(s,it.last,it.changeRate*100,it.volume)}}}}};LaunchedEffect(Unit){refresh()};MaterialTheme(colorScheme=darkColorScheme(primary=V,secondary=C,background=B,surface=P,onBackground=T,onSurface=T)){if(settings){FinalSettings(fa,theme,{theme=it},{fa=!fa}){settings=false};return@MaterialTheme};Scaffold(containerColor=B,topBar={FinalHeader(tab,fa,{tab=3},{settings=true},{fa=!fa})},bottomBar={FinalNav(tab,fa){tab=it}}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(tab){0->FinalHome(fa,quotes,state.report,{pair=it;tab=2},::refresh,{tab=3});1->FinalMarkets(fa,quotes,{pair=it;tab=2;vm.setMarket(it)},::refresh);2->FinalTerminal(fa,pair,{pair=it;vm.setMarket(it)},tf,{tf=it},vm,state);else->FinalIntel(fa,pair,repo)}}}}}}

@Composable private fun FinalHeader(tab:Int,fa:Boolean,ai:()->Unit,set:()->Unit,lang:()->Unit){Row(Modifier.fillMaxWidth().height(64.dp).background(B).padding(horizontal=8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=ai){Icon(Icons.Outlined.Star,null,tint=C)};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(23.dp).clip(RoundedCornerShape(6.dp)).background(Brush.linearGradient(listOf(V,C))),contentAlignment=Alignment.Center){Text("A",color=Color.White,fontWeight=FontWeight.Black)};Spacer(Modifier.width(6.dp));Text("ALVEX",color=T,fontWeight=FontWeight.Black,letterSpacing=2.sp)};Text(if(fa)listOf("خانه","بازار","معاملات و بک‌تست","هوش بازار")[tab]else listOf("Home","Markets","Trading Terminal","Intelligence")[tab],color=M,fontSize=8.sp)};TextButton(onClick=lang){Text(if(fa)"EN"else"FA",color=C,fontSize=9.sp)};IconButton(onClick=set){Icon(Icons.Outlined.Settings,null,tint=T)}}}
@Composable private fun FinalNav(tab:Int,fa:Boolean,go:(Int)->Unit){NavigationBar(containerColor=P,tonalElevation=0.dp){listOf(Triple(0,Icons.Outlined.Home,if(fa)"خانه"else"Home"),Triple(1,Icons.Outlined.List,if(fa)"بازار"else"Markets"),Triple(2,Icons.Outlined.Build,if(fa)"بک‌تست"else"Terminal"),Triple(3,Icons.Outlined.Info,if(fa)"هوش"else"Intel")).forEach{(i,ic,l)->NavigationBarItem(tab==i,{go(i)},icon={Icon(ic,l)},label={Text(l,fontSize=8.sp)})}}}
@Composable private fun FinalHome(fa:Boolean,qs:List<Q>,r:BacktestReport?,open:(String)->Unit,refresh:()->Unit,intel:()->Unit){val btc=qs.firstOrNull{it.s=="BTCUSDT"};val movers=qs.sortedByDescending{it.c}.take(4);LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=20.dp)){item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),colors=CardDefaults.cardColors(containerColor=P)){Box(Modifier.fillMaxWidth().height(150.dp).background(Brush.linearGradient(listOf(Color(0xFF1D1048),P,Color(0xFF071925))),RoundedCornerShape(25.dp))){Column(Modifier.padding(17.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("MARKET OVERVIEW",color=M,fontSize=8.sp,letterSpacing=1.sp);Spacer(Modifier.weight(1f));Pill("LIVE",G)};Spacer(Modifier.height(8.dp));Text("BTC / USDT",color=T,fontSize=12.sp);Text(btc?.let{money(it.p)}?:"—",color=T,fontSize=29.sp,fontWeight=FontWeight.Black);Text(btc?.let{pct(it.c)}?:"Waiting for market data",color=if((btc?.c?:0.0)>=0)G else R,fontSize=10.sp);Spacer(Modifier.height(8.dp));Spark(movers.map{it.c},Modifier.fillMaxWidth().height(30.dp))}}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Stat("BTC",btc?.let{money(it.p)}?:"—",btc?.let{pct(it.c)}?:"—",if((btc?.c?:0)>=0)G else R,Modifier.weight(1f));Stat("24H VOL",qs.firstOrNull()?.let{compact(it.v)}?:"—","CoinEx",C,Modifier.weight(1f));Stat("RADAR",if(qs.isEmpty())"WAIT"else"READY","AI",V,Modifier.weight(1f))}};item{Section("TOP MOVERS",if(fa)"حرکت‌های مهم بازار"else"Live market movers")};items(movers){q->RowCard(q){open(q.s)}};item{Section("AI MARKET RADAR","Pump/Dump • Whale • Meme • Coin Intelligence")};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Radar("PUMP / DUMP",V,Modifier.weight(1f),intel);Radar("WHALE",C,Modifier.weight(1f),intel);Radar("MEME",Y,Modifier.weight(1f),intel)}};item{Section(if(fa)"آخرین بک‌تست"else"LATEST BACKTEST","Real report metrics")};item{Report(r)}}}
@Composable private fun FinalMarkets(fa:Boolean,qs:List<Q>,open:(String)->Unit,refresh:()->Unit){var search by rememberSaveable{mutableStateOf("")};val list=qs.filter{search.isBlank()||it.s.contains(search.uppercase())};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Section(if(fa)"بازار"else"MARKETS","Crypto • Futures • Favorites")};item{OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text(if(fa)"جستجوی ارز"else"Search asset")},leadingIcon={Icon(Icons.Outlined.Search,null)},shape=RoundedCornerShape(16.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Favorites","Crypto","Futures","Forex").forEach{FilterChip(it=="Crypto",{},label={Text(it,fontSize=8.sp)})}}};items(list){q->RowCard(q){open(q.s)}};item{OutlinedButton(onClick=refresh,Modifier.fillMaxWidth()){Icon(Icons.Outlined.Refresh,null);Spacer(Modifier.width(5.dp));Text("Refresh")}}}}
@Composable private fun FinalTerminal(fa:Boolean,pair:String,onPair:(String)->Unit,tf:String,onTf:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){val repo=remember{CoinExRepository()};val scope=rememberCoroutineScope();var cs by remember{mutableStateOf<List<Candle>>(emptyList())};var selected by remember{mutableStateOf<Int?>(null)};fun load(){scope.launch{cs=runCatching{repo.loadKlines(pair,tf,220)}.getOrDefault(emptyList())}};LaunchedEffect(pair,tf){vm.setMarket(pair);vm.setTimeframe(tf);load()};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(9.dp),contentPadding=PaddingValues(bottom=22.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(pair.replace("USDT"," / USDT"),color=T,fontSize=20.sp,fontWeight=FontWeight.Black);Text("CoinEx • real OHLC",color=M,fontSize=8.sp)};Pill(if(state.isRunning)"RUNNING"else"READY",if(state.isRunning)Y else G)}};item{Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("1min","5min","15min","1h","4h","1D").forEach{v->FilterChip(tf==v,{onTf(v)},label={Text(v,fontSize=7.sp)})}}};item{CandleChart(cs,state.report?.trades?:emptyList(),selected,{selected=it},Modifier.fillMaxWidth().height(325.dp))};item{selected?.let{i->cs.getOrNull(i)?.let{Ohlc(it)}}};item{Controls(fa,pair,onPair,vm,state)};item{Report(state.report)};item{state.report?.let{Trades(it.trades,fa)}}}}
@Composable private fun Controls(fa:Boolean,pair:String,onPair:(String)->Unit,vm:BacktestViewModel,state:BacktestUiState){var amount by rememberSaveable{mutableStateOf("1000")};var risk by rememberSaveable{mutableStateOf(state.riskPercent.toString())};var lev by rememberSaveable{mutableStateOf(state.leverage.toString())};Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=P)){Column(Modifier.padding(13.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(if(fa)"تنظیمات بک‌تست"else"BACKTEST CONFIG",color=T,fontWeight=FontWeight.Black);OutlinedTextField(pair,{onPair(it.uppercase())},Modifier.fillMaxWidth(),singleLine=true,label={Text("Pair")});Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(amount,{amount=it},Modifier.weight(1f),singleLine=true,label={Text("Amount")});OutlinedTextField(lev,{lev=it},Modifier.weight(1f),singleLine=true,label={Text("Leverage")})};OutlinedTextField(risk,{risk=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Risk %")});Button(onClick={vm.setRiskPercent(risk.toDoubleOrNull()?:1.0);vm.setLeverage(lev.toDoubleOrNull()?:3.0);vm.runBacktest()},Modifier.fillMaxWidth(),enabled=!state.isRunning,shape=RoundedCornerShape(14.dp)){Icon(Icons.Outlined.PlayArrow,null);Spacer(Modifier.width(5.dp));Text(if(fa)"اجرای بک‌تست واقعی"else"Run real backtest")};Text(state.error?:state.status,color=if(state.error!=null)R else M,fontSize=8.sp)}}}
@Composable private fun FinalIntel(fa:Boolean,pair:String,repo:CoinExRepository){var score by remember{mutableStateOf(0)};var detail by remember{mutableStateOf(if(fa)"در انتظار داده واقعی..."else"Waiting for live data...")};LaunchedEffect(pair){val cs=runCatching{repo.loadKlines(pair,"15min",120)}.getOrDefault(emptyList());val s=PumpDumpDetector().analyze(cs);if(s!=null){score=s.score.toInt();detail="${s.direction} • ${"%.2f".format(s.priceChangePercent)}% • volume x${"%.1f".format(s.volumeRatio)}"}};LazyColumn(Modifier.fillMaxSize().padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Section(if(fa)"هوش بازار"else"INTELLIGENCE HUB","AI Radar • Whale • Pump/Dump • Meme • Coin Intelligence")};item{Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(25.dp),colors=CardDefaults.cardColors(containerColor=P)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Gauge(score);Text(pair,color=T,fontSize=22.sp,fontWeight=FontWeight.Black);Text(detail,color=M,fontSize=9.sp);Text(if(fa)"داده قابل‌اندازه‌گیری؛ پیش‌بینی قطعی نیست."else"Measurable data only; no guaranteed prediction.",color=M,fontSize=8.sp)}}};item{Intel("PUMP / DUMP RADAR","Price acceleration • volume anomaly • score",V)};item{Intel("WHALE INTELLIGENCE","Provider-neutral smart-money layer",C)};item{Intel("MEME / SHITCOIN SCANNER","Liquidity • volatility • concentration • risk",Y)};item{Intel("COIN INTELLIGENCE","Tokenomics • project • team • roadmap • on-chain",G)};item{Intel("AI TRADE ANALYST","Backtest diagnostics and optimization context",V)}}}
@Composable private fun CandleChart(cs:List<Candle>,ts:List<TradeResult>,sel:Int?,pick:(Int)->Unit,m:Modifier){if(cs.isEmpty()){Box(m.clip(RoundedCornerShape(20.dp)).background(P2),contentAlignment=Alignment.Center){Text("Loading real CoinEx candles…",color=M)};return};Canvas(m.clip(RoundedCornerShape(20.dp)).background(P2).pointerInput(cs){detectTapGestures{p->pick(((p.x/size.width)*cs.size).toInt().coerceIn(0,cs.lastIndex))}}){val lo=cs.minOf{it.low};val hi=cs.maxOf{it.high};val range=(hi-lo).takeIf{it>0}?:1.0;val step=size.width/cs.size;val body=(step*.6f).coerceAtLeast(2f);fun y(v:Double)=size.height-((v-lo)/range*size.height).toFloat();for(i in 0..3)drawLine(Color(0xFF1B2B3D),Offset(0f,size.height*i/3f),Offset(size.width,size.height*i/3f),1f);cs.forEachIndexed{i,c->val x=i*step+step/2;val col=if(c.close>=c.open)G else R;drawLine(col,Offset(x,y(c.high)),Offset(x,y(c.low)),1.2f);drawRect(col,Offset(x-body/2,y(maxOf(c.open,c.close))),androidx.compose.ui.geometry.Size(body,maxOf(2f,abs(y(c.open)-y(c.close)))))};ts.forEach{t->val ei=cs.indices.minByOrNull{abs(cs[it].timestamp-t.entryTime)}?:return@forEach;val x=ei*step+step/2;val col=if(t.side==Side.LONG)G else R;drawCircle(col,5f,Offset(x,y(t.entryPrice)));val ex=cs.indices.minByOrNull{abs(cs[it].timestamp-t.exitTime)};if(ex!=null){val xx=ex*step+step/2;drawCircle(Y,4f,Offset(xx,y(t.exitPrice)));drawLine(col,Offset(x,y(t.entryPrice)),Offset(xx,y(t.exitPrice)),1f)}};sel?.let{i->drawLine(T,Offset(i*step+step/2,0f),Offset(i*step+step/2,size.height),1f)}}}
@Composable private fun Trades(ts:List<TradeResult>,fa:Boolean){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text(if(fa)"معاملات و خطایابی ربات"else"TRADE DIAGNOSTICS",color=T,fontWeight=FontWeight.Black);ts.takeLast(25).asReversed().forEach{t->Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=P)){Column(Modifier.padding(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){Pill(t.side.name,if(t.side==Side.LONG)G else R);Spacer(Modifier.width(7.dp));Text("${money(t.entryPrice)} → ${money(t.exitPrice)}",color=T,fontSize=9.sp);Spacer(Modifier.weight(1f));Text("%+.3f".format(t.netPnl),color=if(t.netPnl>=0)G else R,fontWeight=FontWeight.Black,fontSize=9.sp)};Text("SL ${money(t.stopLoss)} • TP ${money(t.takeProfit)} • ${t.exitReason}",color=M,fontSize=8.sp);Text("Qty ${"%.5f".format(t.quantity)} • Fee ${"%.4f".format(t.fees)} • Funding ${"%.4f".format(t.funding)}",color=M,fontSize=7.sp)}}}}}
@Composable private fun Report(r:BacktestReport?){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=P)){Column(Modifier.padding(13.dp)){Text("AI BACKTEST ANALYST",color=T,fontWeight=FontWeight.Black);Spacer(Modifier.height(7.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){Box(Modifier.width(70.dp)){Metric("ROI",r?.let{"%.2f%%".format(it.roiPercent)}?:"—")};Box(Modifier.width(70.dp)){Metric("WIN",r?.let{"%.1f%%".format(it.winRatePercent)}?:"—")};Box(Modifier.width(70.dp)){Metric("PF",r?.let{if(it.profitFactor.isInfinite())"∞" else "%.2f".format(it.profitFactor)}?:"—")};Box(Modifier.width(70.dp)){Metric("DD",r?.let{"%.2f%%".format(it.maxDrawdownPercent)}?:"—")}};Equity(r?.equityCurve?:emptyList(),Modifier.fillMaxWidth().height(60.dp))}}}
@Composable private fun FinalSettings(fa:Boolean,mode:AppThemeMode,onMode:(AppThemeMode)->Unit,toggle:()->Unit,back:()->Unit){Column(Modifier.fillMaxSize().background(B)){Row(Modifier.fillMaxWidth().padding(8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Outlined.ArrowBack,null,tint=T)};Column{Text("ALVEX",color=T,fontWeight=FontWeight.Black);Text(if(fa)"تنظیمات"else"Settings",color=M,fontSize=8.sp)}};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Setting("Account & Security","Session • password • API-key policy",Icons.Outlined.Person)};item{Setting("Notifications","Pump/Dump • Whale • AI alerts",Icons.Outlined.Notifications)};item{Setting("Language",if(fa)"فارسی / English"else"English / فارسی",Icons.Outlined.Language,toggle)};item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Theme",color=T,fontWeight=FontWeight.Bold);Text(if(mode==AppThemeMode.DARK)"Dark"else"Light",color=M,fontSize=8.sp)};Switch(checked=mode==AppThemeMode.LIGHT,onCheckedChange={onMode(if(it)AppThemeMode.LIGHT else AppThemeMode.DARK)})}};item{Setting("Share & Reports","CSV • JSON • AI report • Android share",Icons.Outlined.Share)};item{Setting("About ALVEX","Professional crypto intelligence workspace",Icons.Outlined.Info)}}}}
@Composable private fun Setting(t:String,s:String,ic:androidx.compose.ui.graphics.vector.ImageVector,onClick:(()->Unit)?=null){Card(onClick=onClick?:{},Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=P)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(ic,null,tint=C);Spacer(Modifier.width(9.dp));Column{Text(t,color=T,fontWeight=FontWeight.Bold);Text(s,color=M,fontSize=8.sp)}}}}
@Composable private fun Section(t:String,s:String=""){Column{Text(t,color=T,fontSize=15.sp,fontWeight=FontWeight.Black);if(s.isNotBlank())Text(s,color=M,fontSize=8.sp)}}
@Composable private fun Pill(t:String,c:Color){Box(Modifier.clip(RoundedCornerShape(30.dp)).background(c.copy(.12f)).padding(horizontal=8.dp,vertical=4.dp)){Text(t,color=c,fontSize=7.sp,fontWeight=FontWeight.Black)}}
@Composable private fun Stat(t:String,v:String,s:String,c:Color,m:Modifier){Card(m,shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=P)){Column(Modifier.padding(9.dp)){Text(t,color=M,fontSize=7.sp);Text(v,color=T,fontSize=10.sp,fontWeight=FontWeight.Black);Text(s,color=c,fontSize=7.sp)}}}
@Composable private fun RowCard(q:Q,on:()->Unit){Card(onClick=on,Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=P)){Row(Modifier.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(12.dp)).background(Brush.linearGradient(listOf(V.copy(.2f),C.copy(.1f)))),contentAlignment=Alignment.Center){Text(q.s.take(1),color=T,fontWeight=FontWeight.Black)};Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(q.s.removeSuffix("USDT"),color=T,fontWeight=FontWeight.Bold);Text("/ USDT • ${compact(q.v)} vol",color=M,fontSize=7.sp)};Column(horizontalAlignment=Alignment.End){Text(money(q.p),color=T,fontSize=9.sp,fontWeight=FontWeight.Bold);Text(pct(q.c),color=if(q.c>=0)G else R,fontSize=9.sp)}}}}
@Composable private fun Radar(t:String,c:Color,m:Modifier,on:()->Unit){Card(onClick=on,modifier=m,shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=P2)){Column(Modifier.padding(9.dp)){Pill("•",c);Spacer(Modifier.height(4.dp));Text(t,color=T,fontSize=8.sp,fontWeight=FontWeight.Bold)}}}
@Composable private fun Intel(t:String,s:String,c:Color){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=P)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(39.dp).clip(RoundedCornerShape(11.dp)).background(c.copy(.12f)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Info,null,tint=c)};Spacer(Modifier.width(9.dp));Column{Text(t,color=T,fontSize=10.sp,fontWeight=FontWeight.Black);Text(s,color=M,fontSize=7.sp)}}}}
@Composable private fun Ohlc(c:Candle){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=P)){Row(Modifier.fillMaxWidth().padding(9.dp),horizontalArrangement=Arrangement.SpaceEvenly){Text("O ${money(c.open)}",color=T,fontSize=8.sp);Text("H ${money(c.high)}",color=G,fontSize=8.sp);Text("L ${money(c.low)}",color=R,fontSize=8.sp);Text("C ${money(c.close)}",color=T,fontSize=8.sp);Text("V ${compact(c.volume)}",color=M,fontSize=8.sp)}}}
@Composable private fun Gauge(score:Int){Canvas(Modifier.size(125.dp)){for(i in 1..3)drawCircle(Color(0xFF1B2B3D),size.minDimension*.34f*i/3f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(1f));drawCircle(if(score>=70)R else V,size.minDimension*.18f,center);drawCircle(C,size.minDimension*.34f,center,style=androidx.compose.ui.graphics.drawscope.Stroke(2f))}}
@Composable private fun Metric(t:String,v:String){Column{Text(t,color=M,fontSize=7.sp);Text(v,color=T,fontSize=9.sp,fontWeight=FontWeight.Black)}}
@Composable private fun Equity(v:List<Double>,m:Modifier){Canvas(m){if(v.size<2)return@Canvas;val lo=v.minOrNull()?:0.0;val hi=v.maxOrNull()?:1.0;val r=(hi-lo).takeIf{it>0}?:1.0;for(i in 1 until v.size){val x1=size.width*(i-1)/(v.lastIndex.toFloat());val x2=size.width*i/(v.lastIndex.toFloat());val y1=size.height-((v[i-1]-lo)/r*size.height).toFloat();val y2=size.height-((v[i]-lo)/r*size.height).toFloat();drawLine(V,Offset(x1,y1),Offset(x2,y2),2f)}}}
@Composable private fun Spark(v:List<Double>,m:Modifier){Canvas(m){if(v.size<2)return@Canvas;val lo=v.minOrNull()?:0.0;val hi=v.maxOrNull()?:1.0;val r=(hi-lo).takeIf{it>0}?:1.0;var last=Offset(0f,size.height);v.forEachIndexed{i,x->val p=Offset(size.width*i/(v.lastIndex.toFloat()),size.height-((x-lo)/r*size.height).toFloat());if(i>0)drawLine(C,last,p,2f);last=p}}}
private fun money(v:Double)=if(v>=1000)"%,.2f".format(v)else if(v>=1)"%.4f".format(v)else"%.8f".format(v)
private fun pct(v:Double)="%+.2f%%".format(v)
private fun compact(v:Double)=when{v>=1e9->"%.1fB".format(v/1e9);v>=1e6->"%.1fM".format(v/1e6);v>=1e3->"%.1fK".format(v/1e3);else->"%.0f".format(v)}
